name: migration_poc/hello-world
on:
  workflow_dispatch:
jobs:
  Build-to-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '8'
    - name: Run Maven
      run: mvn clean package
  Unit-Test-to-unit-Test:
    runs-on: ubuntu-latest
    needs:
    - Build-to-build
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '8'
    - name: Run Maven
      run: mvn clean test
    # - name: Publish test results
    #  uses: EnricoMi/publish-unit-test-result-action@v2.12.0
    #  if: always()
    #  with:
    #    junit_files: "**/target/surefire-reports/*.xml"
  Integration-Test-to-integration-test:
    runs-on: ubuntu-latest
    needs:
    - Build-to-build
    - Unit-Test-to-unit-Test
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '8'
    - name: Run Maven
      run: mvn clean verify
    #- name: Publish test results
    #  uses: EnricoMi/publish-unit-test-result-action@v2.12.0
    #  if: always()
    #  with:
    #    junit_files: "**/target/surefire-reports/*.xml"
  Release-to-upload-artifact:
    runs-on: ubuntu-latest
    #environment:
      #name: approval_required
    needs:
    - Build-to-build
    - Unit-Test-to-unit-Test
    - Integration-Test-to-integration-test
    steps:
    - uses: trstringer/manual-approval@v1
      with:
        approvers: vpgitops45
    - uses: actions/checkout@v4.1.0
    - uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '8'
    - name: Run Maven
      run: mvn clean package
    - run: "ls -ltr \n\n####################################\n\ncd target\nls -ltr\n\n####################################"
    - uses: actions/upload-artifact@v4.1.0
      with:
        name: POC-HEL_app.jar
        path: "**/*.jar"
        if-no-files-found: ignore
